# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_moteur_voiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='moteur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Moteur',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
